SERIAL_DRIVER = vendor

ENCODER_MAP_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pimoroni_trackball
POINTING_DEVICE_SPLITS = yes
POINTING_DEVICE_COMBINED = yes
I2C_DRIVER_REQUIRED = yes